import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-start justify-start p-4">
        <div>
          <h1 className="text-6xl">안전 담당자를 위한 최고의 가이드 툴</h1>
          <p className="text-3xl text-gray-600">
            완벽한 안전보건관리 업무체계를 통해 경력 없이도 누구나 쉽고 편하게
          </p>
        </div>
        <div>
          <h2 className="text-xl">후기</h2>
        </div>
        <div className="flex w-full justify-center">
          <button
            type="submit"
            className="mt-6 flex items-center justify-center rounded-md border border-transparent bg-yellow-400 py-3 px-8 text-base font-medium text-white hover:bg-yellow-500"
          >
            무료 체험하러 가기
          </button>
        </div>
      </main>
    </>
  );
};

export default Home;
